<?php
$translate = $this->plugin('translate');
$singleItemSetLabel = ($this->themeSetting('singular_item_set_label')) ? $this->themeSetting('singular_item_set_label') : $translate('item set');
$pluralItemSetLabel = ($this->themeSetting('plural_item_set_label')) ? $this->themeSetting('plural_item_set_label') : $translate('item sets');
$pluralItemLabel = ($this->themeSetting('plural_item_label')) ? $this->themeSetting('plural_item_label') : $translate('items');
// Prepare the item set queries
$ids = isset($query['item_set_id']) ? $query['item_set_id'] : [];
if (!is_array($ids)) {
    $ids = [$ids];
}
$ids = array_filter($ids);
if (!$ids) {
    $ids = [null];
}

if ($this->status()->isSiteRequest()) {
    if (!$this->layout()->site->siteItemSets()) {
        return;
    }
    $filterLocale = (bool) $this->siteSetting('filter_locale_values');
    $lang = $this->lang();

    $selectOptions = [
        'disable_group_by_owner' => true,
        'query' => ['site_id' => $this->layout()->site->id()],
        'lang' => ($filterLocale == 1 ? $lang : null),
        'empty_option' => $translate(sprintf('Select %s...', $singleItemSetLabel))
    ];
} else {
    $selectOptions = [];
}
?>
<div id="item-sets" class="field removable multi-value" role="group">
    <div class="field-meta">
        <span id="by-item-set-label" class="label"><?php echo $translate(sprintf('Search by %s', $singleItemSetLabel)); ?></span>
        <?php echo $this->hyperlink('', '#', ['class' => 'expand', 'title' => $translate('Expand')]); ?>
        <div class="collapsible">
            <div class="field-description"><?php echo $translate(sprintf('Searches for %s that are assigned to any of these %s.', $pluralItemLabel, $pluralItemSetLabel)); ?></div>
        </div>
        <button type="button" class="add-value o-icon-add button" aria-label="<?php echo $translate(sprintf('Add new %s', $singleItemSetLabel)); ?>" title="<?php echo $translate(sprintf('Add new %s', $singleItemSetLabel)); ?>"></button>
    </div>
    <div class="inputs">
        <?php foreach ($ids as $id): ?>
        <div class="value">
            <?php echo $this->itemSetSelect([
                'name' => 'item_set_id[]',
                'attributes' => [
                    'value' => $id,
                    'aria-labelledby' =>  'by-item-set-label'
                ],
                'options' => $selectOptions,
            ]); ?>
            <button type="button" class="o-icon-delete remove-value button" aria-label="<?php echo $translate('Remove value'); ?>" title="<?php echo $translate('Remove value'); ?>"></button>
        </div>
        <?php endforeach; ?>
    </div>
</div>
