<?php
$translate = $this->plugin('translate');
$singleItemSetLabel = ($this->themeSetting('singular_item_set_label')) ? ucwords($this->themeSetting('singular_item_set_label')) : $translate('Item Set');
$this->htmlElement('body')->appendAttribute('class', 'item-sets search');
?>

<h2><?php echo $translate(sprintf('Advanced %s Search', $singleItemSetLabel)); ?></h2>
<form id="advanced-search" method="get" action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">
<?php echo $this->partial(
    'common/advanced-search',
    ['query' => $this->params()->fromQuery(), 'resourceType' => 'itemSet']
); ?>
<div id="page-actions">
    <input type="submit" name="submit" value="<?php echo $this->escapeHtml($translate('Search')); ?>">
</div>
</form>
